### ISSUE TITLE
Trace of the vertical line

### ISSUE THREAD

**Issue by Sirikid** [phallus/fonts#10]
On screen remains the top pixel of the vertical line ```|```.
![example](https://cloud.githubusercontent.com/assets/4840430/6603077/d7e24134-c830-11e4-9474-8ba972b90445.png)

**Comment by Bfgeshka** [comment]
Same font, fresh htop version, everything is shown correctly.

Check your terminal settings.

**Comment by Sirikid** [comment]
[My configs](https://github.com/Sirikid/dotfiles/blob/master/Xresources)
