### ISSUE TITLE
Error installing from AUR

### ISSUE THREAD

**Issue by rosshadden** [phallus/fonts#20]
I am getting the following error when trying to install from the AUR:

```
ucs2any: FONT name in 'lemon-ISO8859-15.bdf' is '-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-15' and not '*-ISO10646-1'!
```

Here is a screenshot of the error, in case the additional context is helpful:

![2016-08-03-09 30 26](https://cloud.githubusercontent.com/assets/669012/17367170/f6279c5c-595c-11e6-8b4e-361cb5b93e71.png)

**Comment by phallus** [comment]
I do not maintain the AUR package. Try installing directly from git.

**Comment by rosshadden** [comment]
Oh, my bad. I'll reopen if the problem still exists.
