### ISSUE TITLE
ttf version of lemon

### ISSUE THREAD

**Issue by fennerm** [phallus/fonts#24]
Hey I created a [ttf version of lemon](http://github.com/fennerm/artwiz-lemon-ttf). I figure it would be more use to people if it were included in your repo, so I was wondering if you'd like me to migrate it over?

I can just keep my repo separate if its not worth the maintenance burden. Though maybe providing a link in your README would be useful to some people.

Thanks!

**Edit:** Fixed broken link

**Comment by phallus** [comment]
Link added to readme.
