### ISSUE TITLE
Russian letter Er in the wrong place

### ISSUE THREAD

**Issue by Zorgodon** [phallus/fonts#26]
This font has the Er letter for U+450 https://www.fileformat.info/info/unicode/char/0450/index.htm
It should be for U+420 https://www.fileformat.info/info/unicode/char/0420/index.htm
This should be added to the bdf:

``
STARTCHAR uni0420
ENCODING 1056
SWIDTH 480 0
DWIDTH 5 0
BBX 5 6 0 0
BITMAP
70
48
48
70
40
40
ENDCHAR

``

**Comment by phallus** [comment]
Fixed.
